"""Generate exact, model-independent artifacts for the controlled posterior experiments."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from mats_experiments.controlled_posterior import (
    ExperimentConfig,
    N8Config,
    build_elicitation_controls,
    build_ladder_examples,
    build_n8_examples,
    fraction_string,
    serialize_example,
    write_jsonl,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("artifacts/controlled_posterior"),
        help="Destination for JSONL artifacts.",
    )
    parser.add_argument("--n8-schedules", type=int, default=32)
    parser.add_argument(
        "--include-endpoints",
        action="store_true",
        help="Add r=0 and r=1 diagnostic replays; interior reliabilities remain primary.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    ladder = build_ladder_examples(
        ExperimentConfig(include_endpoint_diagnostics=args.include_endpoints)
    )
    n8 = build_n8_examples(
        N8Config(num_schedules=args.n8_schedules),
        include_endpoint_diagnostics=args.include_endpoints,
    )
    controls = build_elicitation_controls()

    write_jsonl(args.output_dir / "ladder.jsonl", [serialize_example(row) for row in ladder])
    write_jsonl(args.output_dir / "n8_fixed_bank.jsonl", [serialize_example(row) for row in n8])
    control_records = []
    for control in controls:
        record = asdict(control)
        record["left_weight"] = fraction_string(control.left_weight)
        record["right_weight"] = fraction_string(control.right_weight)
        control_records.append(record)
    write_jsonl(args.output_dir / "elicitation_controls.jsonl", control_records)

    manifest = {
        "ladder_examples": len(ladder),
        "ladder_probes": sum(len(example.probes) for example in ladder),
        "n8_examples": len(n8),
        "n8_probes": sum(len(example.probes) for example in n8),
        "elicitation_controls": len(controls),
        "n8_schedules": args.n8_schedules,
        "include_endpoint_diagnostics": args.include_endpoints,
        "independent_n8_question_schedules": args.n8_schedules,
        "notes": [
            "Reliability replays, probe orientations, and label permutations are paired observations.",
            "At r=0 or r=1, zero-prior-predictive histories are omitted because no posterior exists.",
            "Model-scoring output is generated by notebook 03 and is not part of these artifacts.",
        ],
    }
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
